version: '3.8'

services:
  downmidia:
    build: .
    container_name: downmidia-api
    ports:
      - "8080:8080"
    volumes:
      - downloads:/app/downloads
    restart: unless-stopped # // reiniciar a menos que seja parado

volumes:
  downloads: